name: Integrate Branches

on:
    pull_request:
        branches:
            main
    workflow_dispatch:

jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Merge and Cleanup
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                git config --global user.name "github-actions[bot]"
                git config --global user.email "github-actions[bot]@users.noreply.github.com"

                # Fetch the feature branch
                git fetch origin ${{ github.head_ref }}

                # Checkout the target branch (main or development)
                git checkout ${{ github.base_ref }}

                # Merge the feature branch into the target branch
                git merge origin/${{ github.head_ref }} --no-ff -m "Automated merge from ${{ github.head_ref }} to ${{ github.base_ref }}"

                # Push changes to the target branch
                git push origin ${{ github.base_ref }}

                # Delete the feature branch if it's not develop or main
                if [[ "${{ github.head_ref }}" != "develop" && "${{ github.head_ref }}" != "main" ]]; then
                    echo "Deleting feature branch: ${{ github.head_ref }}"
                    git push origin --delete ${{ github.head_ref }}
                else
                    echo "Skipping deletion for protected branch: ${{ github.head_ref }}"
                fi
